<?
$PERM["yandex_run.php"]["2"]="X";
$PERM["yandex_run.php"]["5"]="X";
$PERM["yandex_run.php"]["3"]="X";
$PERM["yandex_run.php"]["4"]="X";
$PERM["yandex_run.php"]["8"]="X";
$PERM["yandex_run.php"]["6"]="X";
$PERM["yandex_run.php"]["7"]="X";
$PERM["yandex_run.php"]["*"]="X";
?>